import { readFile, writeFile } from "node:fs/promises";
import { allCases } from "./runner.mjs";
const file = new URL("./catalog.json", import.meta.url);
const catalog = JSON.parse(await readFile(file, "utf8"));
for (const requirement of catalog.requirements)
  requirement.tests = allCases
    .filter((c) => c.requirements.includes(requirement.id))
    .map((c) => c.id)
    .sort();
await writeFile(file, `${JSON.stringify(catalog, null, 2)}\n`);
const rows = catalog.requirements.map(
  (r) =>
    `| ${r.id} | ${r.category} | ${r.required ? "required" : "N/A"} | ${r.tests.join(", ") || "GAP: no independent case"} | ${r.evidenceGap ?? r.reason ?? "See executed report; mapping alone is not PASS"} |`,
);
await writeFile(
  new URL("../docs/conformance-matrix.md", import.meta.url),
  `# Entity Event v0.1 conformance evidence map\n\nGenerated by \`node conformance/generate-matrix.mjs\`. This is the planned/executable mapping, not a passing report. All applicable gaps block the full gate. No internal unit/integration result substitutes for independent evidence.\n\n| Requirement | Category | Gate | Independent case IDs | Evidence limit |\n| --- | --- | --- | --- | --- |\n${rows.join("\n")}\n`,
);
