import { quotePostgreSqlIdentifier } from "./identifiers.js";
import type {
  PostgreSqlColumn,
  PostgreSqlConstraint,
  PostgreSqlIndex,
  PostgreSqlStorageIr,
  PostgreSqlTable,
} from "./storage-ir.js";

export function renderPostgreSqlSchema(ir: PostgreSqlStorageIr): string {
  const namespace = quotePostgreSqlIdentifier(ir.provider.namespace);
  const statements: string[] = [`CREATE SCHEMA IF NOT EXISTS ${namespace};`];

  for (const table of ir.tables) {
    statements.push(renderTable(namespace, table));
  }
  for (const table of ir.tables) {
    for (const foreignKey of table.constraints.filter(
      (item) => item.kind === "foreignKey",
    )) {
      statements.push(renderForeignKey(namespace, table, foreignKey));
    }
  }
  for (const table of ir.tables) {
    for (const index of table.indexes) {
      statements.push(renderIndex(namespace, table, index));
    }
  }
  return `${statements.join("\n\n")}\n`;
}

function renderTable(namespace: string, table: PostgreSqlTable): string {
  const definitions = [
    ...table.columns.map(renderColumn),
    ...table.constraints
      .filter((item) => item.kind !== "foreignKey")
      .map(renderInlineConstraint),
  ];
  return [
    `CREATE TABLE ${namespace}.${quotePostgreSqlIdentifier(table.name)} (`,
    definitions.map((definition) => `  ${definition}`).join(",\n"),
    ");",
  ].join("\n");
}

function renderColumn(column: PostgreSqlColumn): string {
  const tokens = [quotePostgreSqlIdentifier(column.name), column.type];
  if (column.generated === "identity")
    tokens.push("GENERATED BY DEFAULT AS IDENTITY");
  if (column.defaultSql !== null) tokens.push(`DEFAULT ${column.defaultSql}`);
  if (!column.nullable) tokens.push("NOT NULL");
  return tokens.join(" ");
}

function renderInlineConstraint(constraint: PostgreSqlConstraint): string {
  const prefix = `CONSTRAINT ${quotePostgreSqlIdentifier(constraint.name)}`;
  if (constraint.kind === "check")
    return `${prefix} CHECK (${constraint.expression ?? "FALSE"})`;
  const columns = renderColumnList(constraint.columns);
  if (constraint.kind === "primaryKey")
    return `${prefix} PRIMARY KEY (${columns})`;
  return `${prefix} UNIQUE (${columns})`;
}

function renderForeignKey(
  namespace: string,
  table: PostgreSqlTable,
  constraint: PostgreSqlConstraint,
): string {
  const reference = constraint.references;
  if (!reference)
    throw new TypeError(
      `Foreign key ${constraint.semanticId} has no reference target.`,
    );
  return [
    `ALTER TABLE ${namespace}.${quotePostgreSqlIdentifier(table.name)}`,
    `  ADD CONSTRAINT ${quotePostgreSqlIdentifier(constraint.name)}`,
    `  FOREIGN KEY (${renderColumnList(constraint.columns)})`,
    `  REFERENCES ${namespace}.${quotePostgreSqlIdentifier(reference.table)} (${quotePostgreSqlIdentifier(reference.column)})`,
    `  ON DELETE ${reference.onDelete} ON UPDATE ${reference.onUpdate};`,
  ].join("\n");
}

function renderIndex(
  namespace: string,
  table: PostgreSqlTable,
  index: PostgreSqlIndex,
): string {
  const unique = index.unique ? "UNIQUE " : "";
  const where = index.where ? ` WHERE ${index.where}` : "";
  return `CREATE ${unique}INDEX ${quotePostgreSqlIdentifier(index.name)} ON ${namespace}.${quotePostgreSqlIdentifier(table.name)} (${renderColumnList(index.columns)})${where};`;
}

function renderColumnList(columns: readonly string[]): string {
  return columns.map(quotePostgreSqlIdentifier).join(", ");
}
